import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js';
import { PERSONA_REGISTRY, searchPersona, buildKnowledgeGraph } from './persona-registry.js';
import { DigitalTwin } from './digital-twin.js';
import { AINavigator, mountNavigator } from './ai-navigator.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],twin=new DigitalTwin(PERSONA_REGISTRY),graph=buildKnowledgeGraph(),navigatorAI=new AINavigator({graph}),state={mode:'EXPLORATION',selectedWorld:null,commandOpen:false};
const worlds=PERSONA_REGISTRY.worlds.map(w=>({...w,type:w.domain,target:'#systems'}));
const setMode=m=>{state.mode=m;document.body.dataset.mode=m.toLowerCase()};const scrollTo=t=>$(t)?.scrollIntoView({behavior:'smooth',block:'start'});
function openWorld(id){const w=worlds.find(x=>x.id===id);if(!w)return;state.selectedWorld=id;twin.enter(w);setMode(`WORLD / ${w.type}`);$$('.system-card').forEach(c=>c.classList.toggle('selected',c.dataset.system===id));scrollTo('#systems');setTimeout(()=>document.querySelector(`[data-system="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),300)}
window.addEventListener('load',()=>setTimeout(()=>$('#boot')?.classList.add('hidden'),1500));
const mount=$('#planet');if(mount){const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.z=3.2;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(mount.clientWidth,mount.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;mount.innerHTML='';mount.appendChild(renderer.domElement);const group=new THREE.Group();scene.add(group);group.add(new THREE.Mesh(new THREE.SphereGeometry(1.32,96,96),new THREE.MeshStandardMaterial({color:0x4d73b5,roughness:.72,metalness:.08,emissive:0x0a1226,emissiveIntensity:.55})));group.add(new THREE.Mesh(new THREE.SphereGeometry(1.39,64,64),new THREE.MeshBasicMaterial({color:0x86b5ff,transparent:true,opacity:.12,side:THREE.BackSide,blending:THREE.AdditiveBlending})));const sg=new THREE.BufferGeometry(),p=new Float32Array(3600);for(let i=0;i<1200;i++){const r=2+Math.random()*1.8,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);p[i*3]=r*Math.sin(b)*Math.cos(a);p[i*3+1]=r*Math.cos(b);p[i*3+2]=r*Math.sin(b)*Math.sin(a)}sg.setAttribute('position',new THREE.BufferAttribute(p,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xb9d1ff,size:.012,transparent:true,opacity:.8})));const nodes=new THREE.Group();for(let i=0;i<6;i++){const n=new THREE.Mesh(new THREE.SphereGeometry(.035,12,12),new THREE.MeshBasicMaterial({color:0xa8c8ff})),a=i/6*Math.PI*2;n.position.set(Math.cos(a)*1.68,Math.sin(a)*.72,Math.sin(a)*.55);nodes.add(n)}group.add(nodes);scene.add(new THREE.DirectionalLight(0xffffff,2.2),new THREE.AmbientLight(0x536b9e,.6));let px=0,py=0,tx=0,ty=0;mount.addEventListener('pointermove',e=>{const r=mount.getBoundingClientRect();ty=((e.clientX-r.left)/r.width-.5)*.6;tx=((e.clientY-r.top)/r.height-.5)*.35});mount.addEventListener('pointerleave',()=>{tx=0;ty=0});function resize(){const w=mount.clientWidth,h=mount.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);function tick(){requestAnimationFrame(tick);px+=(tx-px)*.04;py+=(ty-py)*.04;group.rotation.y+=.0018+py*.002;group.rotation.x=px;nodes.rotation.y-=.003;renderer.render(scene,camera)}tick()}
const hud=document.createElement('div');hud.className='twin-hud';hud.innerHTML='<span class="twin-dot"></span><b>PERSONA TWIN</b><small id="twinState">ONLINE · EXPLORATION</small>';document.body.appendChild(hud);twin.subscribe(s=>{const e=$('#twinState');if(e)e.textContent=`${s.presence} · ${s.focus} · ${s.visits} VISITS`});
const navHud=document.createElement('aside');navHud.className='ai-navigator-hud';navHud.innerHTML='<div class="nav-kicker">KNOWLEDGE GRAPH / AI NAVIGATOR</div><input id="navInput" placeholder="Ask the Persona OS…" aria-label="Ask the AI Navigator"><div id="navOutput" class="nav-output" hidden></div>';document.body.appendChild(navHud);mountNavigator({input:$('#navInput'),output:$('#navOutput'),onWorld:openWorld});
const cc=$('#commandCenter'),input=$('#commandInput'),results=$('#commandResults');const base=[['Go to World Model','home / planetary core',()=>scrollTo('#world')],['Explore System Worlds','projects / worlds',()=>scrollTo('#systems')],['Open Capability Constellation','technology / skills',()=>scrollTo('#capabilities')],['Open Persona Core','identity / philosophy',()=>scrollTo('#persona')],['View System Signal','activity / state',()=>scrollTo('#activity')],['Open Contact Channel','engage / collaborate',()=>scrollTo('#contact')],['Ask AI Navigator','knowledge graph / semantic query',()=>{navHud.scrollIntoView({behavior:'smooth'});$('#navInput')?.focus()}]];
function renderCommands(q=''){const query=q.trim().toLowerCase(),commands=base.map(([label,hint,action])=>({label,hint,action})).concat(searchPersona(query).map(w=>({label:`Enter ${w.name}`,hint:`${w.domain} world`,action:()=>openWorld(w.id)})));const filtered=commands.filter(c=>!query||`${c.label} ${c.hint}`.toLowerCase().includes(query));results.innerHTML=filtered.map((c,i)=>`<button class="command-item"><b>${c.label}</b><small>${c.hint}</small></button>`).join('')||'<div class="command-empty">NO SIGNAL — TRY A WORLD, CAPABILITY, OR TECHNOLOGY</div>';results.querySelectorAll('.command-item').forEach((b,i)=>b.onclick=()=>{filtered[i].action();closeCommand()})}function openCommand(){cc?.classList.add('open');cc?.setAttribute('aria-hidden','false');renderCommands();setTimeout(()=>input?.focus(),40)}function closeCommand(){cc?.classList.remove('open');cc?.setAttribute('aria-hidden','true')}
$('#commandToggle')?.addEventListener('click',openCommand);$('#commandClose')?.addEventListener('click',closeCommand);$('.command-backdrop')?.addEventListener('click',closeCommand);input?.addEventListener('input',e=>renderCommands(e.target.value));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();cc?.classList.contains('open')?closeCommand():openCommand()}if(e.key==='Escape')closeCommand()});
$$('[data-command]').forEach(b=>b.addEventListener('click',()=>{const c=b.dataset.command;if(c==='command')return openCommand();if(c==='systems')return scrollTo('#systems');const w=worlds.find(x=>x.id===c);if(w)openWorld(w.id)}));$$('.planet-hotspot').forEach(b=>b.addEventListener('click',()=>scrollTo(`#${b.dataset.target}`)));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.content-section,.system-card,.cap-node,.signal-grid > div').forEach(e=>{e.classList.add('reveal');observer.observe(e)});const sectionObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)$$('.topbar nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-35% 0px -55% 0px'});$$('main > section[id]').forEach(s=>sectionObserver.observe(s));$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}}));setMode('EXPLORATION');
